# Generated by Django 2.1.15 on 2021-03-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eemail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
